### ISSUE TITLE
Connection schema

### ISSUE THREAD

**Issue by jsam** [slothorpe/SabvotonCommandLineInterface#2]
Hey,

Great work on this and thanks for the spreadsheet. I was wondering if you have a connection schema somewhere as well? Did you use modbus shield if so which one? 

Would something like this one work: https://docs.arduino.cc/hardware/mkr-485-shield ?

Thank you.
Sam.

**Comment by slothorpe** [comment]
Hey and thanx,

as far as I remember the sabvoton uses 5v TTL for the serial Modbus communication, hence you directly connect the serial port of the arduino to the sabvoton. No rs485 Modbus shield needed.

Regards
   Holger

Von meinem iPhone gesendet

**Comment by jsam** [comment]
Thank you for the quick response. I'll give it a try and see what happens. :) 

Closing the issue.
